[package]
name = "verdin-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rust_decimal = "1.43.0"
serde_json = "1.0.151"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls-ring-webpki", "postgres", "mysql", "sqlite", "json", "time", "rust_decimal"] }
thiserror = "2.0.21"
time = { version = "0.3.55", features = ["formatting", "parsing", "macros"] }
tracing = "0.1.44"
url = "2.5.8"

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
