import {
  lucideArrowDown,
  lucideArrowLeft,
  lucideArrowUp,
  lucideBlocks,
  lucideChevronsUpDown,
  lucideCopy,
  lucideDatabase,
  lucideEyeOff,
  lucideFile,
  lucideFileText,
  lucideGlobe,
  lucideGripVertical,
  lucideKeyRound,
  lucideLayoutDashboard,
  lucideLeaf,
  lucideLogOut,
  lucidePencil,
  lucidePlus,
  lucideSave,
  lucideSearch,
  lucideSend,
  lucideShieldCheck,
  lucideTrash2,
  lucideUndo2,
  lucideUsers,
  lucideX,
} from '@ng-icons/lucide';

/** Every icon the admin uses, registered once at bootstrap. */
export const ICONS = {
  lucideArrowDown,
  lucideArrowLeft,
  lucideArrowUp,
  lucideBlocks,
  lucideChevronsUpDown,
  lucideCopy,
  lucideDatabase,
  lucideEyeOff,
  lucideFile,
  lucideFileText,
  lucideGlobe,
  lucideGripVertical,
  lucideKeyRound,
  lucideLayoutDashboard,
  lucideLeaf,
  lucideLogOut,
  lucidePencil,
  lucidePlus,
  lucideSave,
  lucideSearch,
  lucideSend,
  lucideShieldCheck,
  lucideTrash2,
  lucideUndo2,
  lucideUsers,
  lucideX,
};
