[package]
name = "verdin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
clap = { version = "4.6.7", features = ["derive", "env"] }
figment = { version = "0.10.19", features = ["toml", "env"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["trace", "request-id", "timeout", "cors", "limit", "util"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
verdin-db = { version = "0.0.1", path = "../verdin-db" }
verdin-migrate = { version = "0.0.1", path = "../verdin-migrate" }
verdin-schema = { version = "0.0.1", path = "../verdin-schema" }

[lints]
workspace = true

[dev-dependencies]
figment = { version = "0.10.19", features = ["test", "toml", "env"] }
http-body-util = "0.1.5"
serde_json = "1.0.151"
tempfile = "3.27.0"
tower = { version = "0.5.3", features = ["util"] }
