[package]
name = "verdin-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tempfile = "3.27.0"
url = "2.5.8"
verdin-db = { version = "0.1.0", path = "../verdin-db" }

[lints]
workspace = true
