//! DDL rendering per dialect (docs/architecture.md §7.2 and §9.3).
//!
//! Identifiers come only from the validated schema (`^[a-z][a-z0-9_]*$`) and are always
//! quoted, so reserved words are harmless.

use verdin_db::Flavor;

use crate::diff::Change;
use crate::model::{Column, ColumnDefault, ColumnType, Table};

/// Prefix of the temporary table used by SQLite table rebuilds.
const REBUILD_PREFIX: &str = "_vd_new_";

#[derive(Debug, Clone, Copy)]
pub struct Dialect {
    pub flavor: Flavor,
}

impl Dialect {
    pub fn new(flavor: Flavor) -> Self {
        Self { flavor }
    }

    pub fn quote(&self, identifier: &str) -> String {
        debug_assert!(!identifier.contains(['"', '`']), "identifiers are validated upstream");
        if self.flavor.is_mysql_family() {
            format!("`{identifier}`")
        } else {
            format!("\"{identifier}\"")
        }
    }

    fn quote_list(&self, identifiers: &[String]) -> String {
        identifiers.iter().map(|identifier| self.quote(identifier)).collect::<Vec<_>>().join(", ")
    }

    pub fn column_type(&self, ty: ColumnType) -> String {
        use ColumnType::*;
        match self.flavor {
            Flavor::Postgres => match ty {
                Id | BigInt => "bigint".into(),
                Integer => "integer".into(),
                SmallInt => "smallint".into(),
                Double => "double precision".into(),
                Decimal { precision, scale } => format!("numeric({precision},{scale})"),
                Boolean => "boolean".into(),
                Char { length } => format!("char({length})"),
                Varchar { length } => format!("varchar({length})"),
                Text => "text".into(),
                Date => "date".into(),
                Time => "time(3)".into(),
                DateTime => "timestamptz(3)".into(),
                Json => "jsonb".into(),
            },
            Flavor::MySql | Flavor::MariaDb => match ty {
                Id | BigInt => "bigint".into(),
                Integer => "int".into(),
                SmallInt => "smallint".into(),
                Double => "double".into(),
                Decimal { precision, scale } => format!("decimal({precision},{scale})"),
                Boolean => "tinyint(1)".into(),
                Char { length } => format!("char({length})"),
                Varchar { length } => format!("varchar({length})"),
                Text => "longtext".into(),
                Date => "date".into(),
                Time => "time(3)".into(),
                DateTime => "datetime(3)".into(),
                Json => "json".into(),
            },
            // SQLite has type affinities, not types. Exact values (decimals, timestamps)
            // are stored as text so nothing is rounded.
            Flavor::Sqlite => match ty {
                Id | BigInt | Integer | SmallInt | Boolean => "integer".into(),
                Double => "real".into(),
                Decimal { .. }
                | Char { .. }
                | Varchar { .. }
                | Text
                | Date
                | Time
                | DateTime
                | Json => "text".into(),
            },
        }
    }

    pub fn column_definition(&self, column: &Column) -> String {
        let name = self.quote(&column.name);
        if column.ty == ColumnType::Id {
            return match self.flavor {
                Flavor::Postgres => {
                    format!("{name} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                }
                Flavor::MySql | Flavor::MariaDb => {
                    format!("{name} bigint NOT NULL AUTO_INCREMENT PRIMARY KEY")
                }
                Flavor::Sqlite => format!("{name} integer PRIMARY KEY AUTOINCREMENT"),
            };
        }
        let mut definition = format!("{name} {}", self.column_type(column.ty));
        if !column.nullable {
            definition.push_str(" NOT NULL");
        }
        if let Some(default) = &column.default {
            definition.push_str(" DEFAULT ");
            definition.push_str(&default_literal(default));
        }
        definition
    }

    pub fn create_table(&self, table: &Table, if_not_exists: bool) -> String {
        let columns: Vec<_> = table
            .columns
            .iter()
            .map(|column| format!("  {}", self.column_definition(column)))
            .collect();
        let mut sql = format!(
            "CREATE TABLE {}{} (\n{}\n)",
            if if_not_exists { "IF NOT EXISTS " } else { "" },
            self.quote(&table.name),
            columns.join(",\n")
        );
        if let Some(collation) = self.collation() {
            sql.push_str(&format!(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE={collation}"));
        }
        sql
    }

    /// Accent- and case-insensitive Unicode collation for MySQL-family tables.
    pub fn collation(&self) -> Option<&'static str> {
        match self.flavor {
            Flavor::MySql => Some("utf8mb4_0900_ai_ci"),
            Flavor::MariaDb => Some("utf8mb4_uca1400_ai_ci"),
            Flavor::Postgres | Flavor::Sqlite => None,
        }
    }

    pub fn statements(&self, change: &Change) -> Vec<String> {
        let q = |identifier: &str| self.quote(identifier);
        match change {
            Change::RenameTable { from, to } => vec![if self.flavor.is_mysql_family() {
                format!("RENAME TABLE {} TO {}", q(from), q(to))
            } else {
                format!("ALTER TABLE {} RENAME TO {}", q(from), q(to))
            }],
            Change::RenameColumn { table, from, to } => {
                vec![format!("ALTER TABLE {} RENAME COLUMN {} TO {}", q(table), q(from), q(to))]
            }
            Change::DropIndex { table, index } => vec![if self.flavor.is_mysql_family() {
                format!("DROP INDEX {} ON {}", q(&index.name), q(table))
            } else {
                format!("DROP INDEX {}", q(&index.name))
            }],
            Change::CreateTable { table } => vec![self.create_table(table, false)],
            Change::AddColumn { table, column } => {
                vec![format!(
                    "ALTER TABLE {} ADD COLUMN {}",
                    q(table),
                    self.column_definition(column)
                )]
            }
            Change::AlterColumn { table, from, to } => self.alter_column(table, from, to),
            Change::DropColumn { table, column } => {
                vec![format!("ALTER TABLE {} DROP COLUMN {}", q(table), q(&column.name))]
            }
            Change::DropTable { table } => vec![format!("DROP TABLE {}", q(&table.name))],
            Change::CreateIndex { table, index, .. } => vec![format!(
                "CREATE {}INDEX {} ON {} ({})",
                if index.unique { "UNIQUE " } else { "" },
                q(&index.name),
                q(table),
                self.quote_list(&index.columns)
            )],
            Change::RebuildTable { from, to } => self.rebuild_table(from, to),
        }
    }

    fn alter_column(&self, table: &str, from: &Column, to: &Column) -> Vec<String> {
        let table = self.quote(table);
        match self.flavor {
            Flavor::Postgres => {
                let column = self.quote(&to.name);
                let mut actions = Vec::new();
                let type_changed = from.ty != to.ty;
                // A default of the old type may not cast to the new one: drop it first.
                let drop_default_first = type_changed && from.default.is_some();
                if drop_default_first {
                    actions.push(format!("ALTER COLUMN {column} DROP DEFAULT"));
                }
                if type_changed {
                    let ty = self.column_type(to.ty);
                    actions.push(format!("ALTER COLUMN {column} TYPE {ty} USING {column}::{ty}"));
                }
                if from.nullable != to.nullable {
                    let action = if to.nullable { "DROP NOT NULL" } else { "SET NOT NULL" };
                    actions.push(format!("ALTER COLUMN {column} {action}"));
                }
                match &to.default {
                    Some(default)
                        if drop_default_first || from.default.as_ref() != Some(default) =>
                    {
                        actions.push(format!(
                            "ALTER COLUMN {column} SET DEFAULT {}",
                            default_literal(default)
                        ));
                    }
                    None if from.default.is_some() && !drop_default_first => {
                        actions.push(format!("ALTER COLUMN {column} DROP DEFAULT"));
                    }
                    _ => {}
                }
                vec![format!("ALTER TABLE {table} {}", actions.join(", "))]
            }
            Flavor::MySql | Flavor::MariaDb => {
                vec![format!("ALTER TABLE {table} MODIFY COLUMN {}", self.column_definition(to))]
            }
            Flavor::Sqlite => {
                unreachable!("the planner turns SQLite column alterations into rebuilds")
            }
        }
    }

    /// SQLite's documented procedure for schema changes `ALTER TABLE` cannot express:
    /// create the new shape, copy the surviving columns, swap, recreate indexes.
    // M3 (link tables with foreign keys) must disable `foreign_keys` around this.
    fn rebuild_table(&self, from: &Table, to: &Table) -> Vec<String> {
        let temporary = Table { name: format!("{REBUILD_PREFIX}{}", to.name), ..to.clone() };
        let shared: Vec<String> = to
            .columns
            .iter()
            .filter(|column| from.column(&column.name).is_some())
            .map(|column| column.name.clone())
            .collect();
        let shared = self.quote_list(&shared);

        let mut statements = vec![
            self.create_table(&Table { indexes: Vec::new(), ..temporary.clone() }, false),
            format!(
                "INSERT INTO {} ({shared}) SELECT {shared} FROM {}",
                self.quote(&temporary.name),
                self.quote(&from.name)
            ),
            format!("DROP TABLE {}", self.quote(&from.name)),
            format!(
                "ALTER TABLE {} RENAME TO {}",
                self.quote(&temporary.name),
                self.quote(&to.name)
            ),
        ];
        for index in &to.indexes {
            statements.extend(self.statements(&Change::CreateIndex {
                table: to.name.clone(),
                index: index.clone(),
                new_table: true,
            }));
        }
        statements
    }
}

fn default_literal(default: &ColumnDefault) -> String {
    match default {
        ColumnDefault::Text(text) => format!("'{}'", text.replace('\'', "''")),
        ColumnDefault::Int(value) => value.to_string(),
    }
}
