[package]
name = "verdin-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum = "0.8.9"
bytes = "1.12.1"
indexmap = "2.14.2"
serde_json = "1.0.151"
tracing = "0.1.44"
verdin-content = { version = "0.0.1", path = "../verdin-content" }
verdin-db = { version = "0.0.1", path = "../verdin-db" }
verdin-query = { version = "0.0.1", path = "../verdin-query" }
verdin-schema = { version = "0.0.1", path = "../verdin-schema" }

[lints]
workspace = true

[dev-dependencies]
http-body-util = "0.1.5"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.3", features = ["util"] }
verdin-migrate = { path = "../verdin-migrate" }
verdin-schema = { path = "../verdin-schema" }
verdin-testkit = { path = "../verdin-testkit" }
