// Generated by `verdin types`. Do not edit: run `verdin types` again after schema changes.

/** A media library file. */
export interface Media {
  id: number;
  documentId: string;
  name: string;
  alternativeText: string | null;
  caption: string | null;
  width: number | null;
  height: number | null;
  focalPoint: { x: number; y: number } | null;
  formats: Record<string, MediaFormat> | null;
  hash: string;
  ext: string;
  mime: string;
  /** Kilobytes. */
  size: number;
  url: string;
  previewUrl: string | null;
  provider: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
}

export interface MediaFormat {
  name: string;
  hash: string;
  ext: string;
  mime: string;
  width: number;
  height: number;
  size: number;
  sizeInBytes: number;
  url: string;
}

/** Rich text in Strapi's blocks format. */
export type Blocks = Block[];
export type Block =
  | { type: 'paragraph' | 'quote'; children: InlineNode[] }
  | { type: 'heading'; level: 1 | 2 | 3 | 4 | 5 | 6; children: InlineNode[] }
  | { type: 'code'; language?: string | null; children: InlineNode[] }
  | { type: 'list'; format: 'ordered' | 'unordered'; children: Array<ListItem | Extract<Block, { type: 'list' }>> }
  | { type: 'image'; image: Pick<Media, 'url'> & Partial<Media>; children: InlineNode[] };
export interface ListItem {
  type: 'list-item';
  children: InlineNode[];
}
export type InlineNode = TextNode | { type: 'link'; url: string; children: TextNode[] };
export interface TextNode {
  type: 'text';
  text: string;
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  strikethrough?: boolean;
  code?: boolean;
}

/** Fields every document has. */
export interface DocumentBase {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
}

/** Component `blocks.hero`. */
export interface ComponentBlocksHero {
  id: number;
  title: string;
  subtitle: string | null;
}
export interface ComponentBlocksHeroInput {
  id?: number;
  title?: string | null;
  subtitle?: string | null;
}

/** Component `blocks.quote`. */
export interface ComponentBlocksQuote {
  id: number;
  text: string;
  author: string | null;
}
export interface ComponentBlocksQuoteInput {
  id?: number;
  text?: string | null;
  author?: string | null;
}

/** Component `shared.seo`. */
export interface ComponentSharedSeo {
  id: number;
  metaTitle: string | null;
  metaDescription: string | null;
}
export interface ComponentSharedSeoInput {
  id?: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
}

/** `api::article` (collection). */
export interface Article extends DocumentBase {
  title: string;
  slug: string;
  excerpt: string | null;
  body: string | null;
  readingTime: number | null;
  featured: boolean | null;
  category?: Category | null;
  tags?: Tag[];
  seo?: ComponentSharedSeo | null;
  blocks?: Array<(ComponentBlocksHero & { __component: "blocks.hero" }) | (ComponentBlocksQuote & { __component: "blocks.quote" })>;
}
export interface ArticleInput {
  title?: string | null;
  slug?: string | null;
  excerpt?: string | null;
  body?: string | null;
  readingTime?: number | null;
  featured?: boolean | null;
  category?: string | null;
  tags?: string[] | { connect?: Array<string | { documentId: string; position?: unknown }>; disconnect?: string[]; set?: string[] };
  seo?: ComponentSharedSeoInput | null;
  blocks?: Array<(ComponentBlocksHeroInput & { __component: "blocks.hero" }) | (ComponentBlocksQuoteInput & { __component: "blocks.quote" })>;
}

/** `api::category` (collection). */
export interface Category extends DocumentBase {
  name: string;
  articles?: Article[];
}
export interface CategoryInput {
  name?: string | null;
}

/** `api::homepage` (single type). */
export interface Homepage extends DocumentBase {
  headline: string;
  seo?: ComponentSharedSeo | null;
}
export interface HomepageInput {
  headline?: string | null;
  seo?: ComponentSharedSeoInput | null;
}

/** `api::tag` (collection). */
export interface Tag extends DocumentBase {
  label: string;
}
export interface TagInput {
  label?: string | null;
}

/** Collection routes (`/api/{route}`) and their documents, for `@verdin/client`.
 * Type aliases, not interfaces: the client's schema constraint needs their index signature. */
export type Collections = {
  articles: { document: Article; input: ArticleInput };
  categories: { document: Category; input: CategoryInput };
  tags: { document: Tag; input: TagInput };
};

/** Single type routes. */
export type Singles = {
  homepage: { document: Homepage; input: HomepageInput };
};

export interface VerdinSchema {
  collections: Collections;
  singles: Singles;
}
